### PR TITLE
Header Complete

### PR DESCRIPTION
**Pull request by davodey**
http://45.55.127.237/pearson-glp-pl/?p=viewall-ui-kit-header

### CODE REVIEW

**Comment by pauljadam** [comment]
@antelopeb @davodey yes the div logo needs alt text, if it's not a real img element then you can use ARIA role="img" and aria-label="text alternative" e.g. div class="logo" role="img" aria-label="Pearson"

It does not need the string "logo" in the alt text. 

You could also put the actions buttons inside a nav element to get the aria navigation role but that sort of depends on if you consider them navigation or not.

**Comment by pauljadam** [comment]
@davodey one other issue to consider is if the notifications button is setup to handle when there are a number of notifications like 3 will it say "3 new notifications" or something similar?

**Comment by davodey** [comment]
@pauljadam no I don't think so. It's a good idea, but I haven't seen any supporting designs.

**Comment by davodey** [comment]
@pauljadam thank you sir, recommendations have been added. 

I did not add the <nav> tag.  The buttons don't navigate anywhere, and would only be used to toggle some actions, like showing a list of notifications or bringing up a help popup.  

I'm sure it's debatable and some would say its nav..I just don't see it that way.

**Pull request merged**
