### PR TITLE
Table controls

### PR DESCRIPTION
**Pull request by davodey**
This is complete, the search is working good.  I need to add some aria-hidden attributes when filtered, but that's it.

### CODE REVIEW

**Comment by jackiejakob** [comment]
Is the stroke on the rows correct? It doesn't look like it matches: http://pearson-higher-ed.github.io/design/c/tables/

**Comment by davodey** [comment]
Yeah, I double checked, and the grey border is correct.  I missed the border on the selected rows though, so I added that in.

**Comment by jackiejakob** [comment]
Sorry, few more things:
1) Do you think they made the placeholder for "Search" darker or is that inputted text in the UI kit? 
2) It looks like the magnifying glass is grey ($neutral-three) now to me. Should we update?

**Comment by davodey** [comment]
Good questions.  The placeholder text should be concrete.  I think it use to be moonlight, but it got changed due to accessibility contrast issues. They probably forgot to update their images to show the darker placeholder.

An icon displayed inside an input field should be charcoal.  I double checked and that's what we're using, so I think we can leave it.

**Comment by jackiejakob** [comment]
OK cool. Where are the specifications that list the color names? I've just been picking off the sketch file.

**Comment by davodey** [comment]
Im getting them from the redlines on the UXF site.

Tables: http://pearson-higher-ed.github.io/design/c/tables/#redlines
Inputs: http://pearson-higher-ed.github.io/design/c/inputs/#redlines

IMO its really silly that the UI kit and the UXF site don't align right.  It's an ongoing issue that I dont think will ever get fixed.  With that said, well just do the best we can to align with whats available.

**Pull request merged**
